name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build dist
        run: |
          mkdir -p dist
          npx terser src/wa-sticker.js -c -m -o dist/wa-sticker.min.js
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/wa-sticker.min.js
